name: Run Tests with Allure
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: docker build -t api-tests .
    - name: Run tests in Docker
      run: docker run api-tests
    - uses: actions/checkout@v4
    - name: Install Allure
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.zip
        unzip allure-2.29.0.zip
        echo "$PWD/allure-2.29.0/bin" >> $GITHUB_PATH
    - name: Generate Allure report
      run: allure generate allure-results -o allure-report --clean
    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report
